{"rendered": {"reason": {"raw": "We should look into a proper solution later", "markup": "markdown", "html": "<p>We should look into a proper solution later</p>", "type": "rendered"}, "description": {"raw": "While porting code from Gazebo-classic to Ignition, often some Gazebo 9 plugin sneakily hides inside an SDF / URDF file, happens to be on the path and we try to `dlopen` it. The problem is that this mixes 2 different versions of `ign-msgs`, which causes protobuf to throw an exception:\r\n\r\n~~~\r\n[libprotobuf ERROR google/protobuf/descriptor_database.cc:57] File already exists in database: ignition/msgs/time.proto                                                         \r\n[libprotobuf FATAL google/protobuf/descriptor.cc:1164] CHECK failed: generated_database_->Add(encoded_file_descriptor, size):\r\nterminate called after throwing an instance of 'google::protobuf::FatalException'   \r\n  what():  CHECK failed: generated_database_->Add(encoded_file_descriptor, size):  \r\n~~~\r\n\r\nThis causes the whole program to crash, and it's tough for the end user to realize what's going wrong. Ideally, we'd handle this more elegantly. Maybe something can be done on the `ign-msgs` side. But for now, I tried something here.\r\n\r\nThis try/catch block cleanly handles the situation for me, the following is printed, the library is ignored and simulation goes on:\r\n\r\n\r\n```\r\nException thrown while loading library [/home/chapulina/rmf/build/ros1/install/lib/libpayload_handler.so]\r\n[Err] [SystemLoader.cc:75] Failed to load system plugin [libpayload_handler.so] : couldn't load library on path [/home/chapulina/rmf/build/ros1/install/lib/libpayload_handler.s\r\no].\r\n```\r\n\r\nBut the catch (no pun intended) is that if I don't wrap the `dlopen` call with those sleeps, for some reason the program fails to catch protobuf's exception and crashes. I really don't understand how that would matter.\r\n\r\nReading answers like [this](https://stackoverflow.com/questions/413473/dlopen-on-library-with-static-member-that-throws-exception-in-constructor-resu) it sounds like we shouldn't be able to catch that exception in the first place, but somehow the sleeps make it work.", "markup": "markdown", "html": "<p>While porting code from Gazebo-classic to Ignition, often some Gazebo 9 plugin sneakily hides inside an SDF / URDF file, happens to be on the path and we try to <code>dlopen</code> it. The problem is that this mixes 2 different versions of <code>ign-msgs</code>, which causes protobuf to throw an exception:</p>\n<div class=\"codehilite\"><pre><span></span>[libprotobuf ERROR google/protobuf/descriptor_database.cc:57] File already exists in database: ignition/msgs/time.proto                                                         \n[libprotobuf FATAL google/protobuf/descriptor.cc:1164] CHECK failed: generated_database_-&gt;Add(encoded_file_descriptor, size):\nterminate called after throwing an instance of &#39;google::protobuf::FatalException&#39;   \n  what():  CHECK failed: generated_database_-&gt;Add(encoded_file_descriptor, size):  \n</pre></div>\n\n\n<p>This causes the whole program to crash, and it's tough for the end user to realize what's going wrong. Ideally, we'd handle this more elegantly. Maybe something can be done on the <code>ign-msgs</code> side. But for now, I tried something here.</p>\n<p>This try/catch block cleanly handles the situation for me, the following is printed, the library is ignored and simulation goes on:</p>\n<div class=\"codehilite\"><pre><span></span>Exception thrown while loading library [/home/chapulina/rmf/build/ros1/install/lib/libpayload_handler.so]\n[Err] [SystemLoader.cc:75] Failed to load system plugin [libpayload_handler.so] : couldn&#39;t load library on path [/home/chapulina/rmf/build/ros1/install/lib/libpayload_handler.s\no].\n</pre></div>\n\n\n<p>But the catch (no pun intended) is that if I don't wrap the <code>dlopen</code> call with those sleeps, for some reason the program fails to catch protobuf's exception and crashes. I really don't understand how that would matter.</p>\n<p>Reading answers like <a data-is-external-link=\"true\" href=\"https://stackoverflow.com/questions/413473/dlopen-on-library-with-static-member-that-throws-exception-in-constructor-resu\" rel=\"nofollow\">this</a> it sounds like we shouldn't be able to catch that exception in the first place, but somehow the sleeps make it work.</p>", "type": "rendered"}, "title": {"raw": "[WIP] Catch exception thrown during dlopen", "markup": "markdown", "html": "<p>[WIP] Catch exception thrown during dlopen</p>", "type": "rendered"}}, "type": "pullrequest", "description": "While porting code from Gazebo-classic to Ignition, often some Gazebo 9 plugin sneakily hides inside an SDF / URDF file, happens to be on the path and we try to `dlopen` it. The problem is that this mixes 2 different versions of `ign-msgs`, which causes protobuf to throw an exception:\r\n\r\n~~~\r\n[libprotobuf ERROR google/protobuf/descriptor_database.cc:57] File already exists in database: ignition/msgs/time.proto                                                         \r\n[libprotobuf FATAL google/protobuf/descriptor.cc:1164] CHECK failed: generated_database_->Add(encoded_file_descriptor, size):\r\nterminate called after throwing an instance of 'google::protobuf::FatalException'   \r\n  what():  CHECK failed: generated_database_->Add(encoded_file_descriptor, size):  \r\n~~~\r\n\r\nThis causes the whole program to crash, and it's tough for the end user to realize what's going wrong. Ideally, we'd handle this more elegantly. Maybe something can be done on the `ign-msgs` side. But for now, I tried something here.\r\n\r\nThis try/catch block cleanly handles the situation for me, the following is printed, the library is ignored and simulation goes on:\r\n\r\n\r\n```\r\nException thrown while loading library [/home/chapulina/rmf/build/ros1/install/lib/libpayload_handler.so]\r\n[Err] [SystemLoader.cc:75] Failed to load system plugin [libpayload_handler.so] : couldn't load library on path [/home/chapulina/rmf/build/ros1/install/lib/libpayload_handler.s\r\no].\r\n```\r\n\r\nBut the catch (no pun intended) is that if I don't wrap the `dlopen` call with those sleeps, for some reason the program fails to catch protobuf's exception and crashes. I really don't understand how that would matter.\r\n\r\nReading answers like [this](https://stackoverflow.com/questions/413473/dlopen-on-library-with-static-member-that-throws-exception-in-constructor-resu) it sounds like we shouldn't be able to catch that exception in the first place, but somehow the sleeps make it work.", "links": {"decline": {"href": "https://api.bitbucket.org/2.0/repositories/ignitionrobotics/ign-plugin/pullrequests/34/decline"}, "diffstat": {"href": "https://api.bitbucket.org/2.0/repositories/ignitionrobotics/ign-plugin/diffstat/ignitionrobotics/ign-plugin:ba4e61bb9898%0D6689cfd44b98?from_pullrequest_id=34"}, "commits": {"href": "data/repositories/ignitionrobotics/ign-plugin/pullrequests/34/commits.json"}, "self": {"href": "data/repositories/ignitionrobotics/ign-plugin/pullrequests/34.json"}, "comments": {"href": "data/repositories/ignitionrobotics/ign-plugin/pullrequests/34/comments_page=1.json"}, "merge": {"href": "https://api.bitbucket.org/2.0/repositories/ignitionrobotics/ign-plugin/pullrequests/34/merge"}, "html": {"href": "#!/ignitionrobotics/ign-plugin/pull-requests/34"}, "activity": {"href": "data/repositories/ignitionrobotics/ign-plugin/pullrequests/34/activity.json"}, "diff": {"href": "https://api.bitbucket.org/2.0/repositories/ignitionrobotics/ign-plugin/diff/ignitionrobotics/ign-plugin:ba4e61bb9898%0D6689cfd44b98?from_pullrequest_id=34"}, "approve": {"href": "https://api.bitbucket.org/2.0/repositories/ignitionrobotics/ign-plugin/pullrequests/34/approve"}, "statuses": {"href": "data/repositories/ignitionrobotics/ign-plugin/pullrequests/34/statuses_page=1.json"}}, "title": "[WIP] Catch exception thrown during dlopen", "close_source_branch": false, "reviewers": [], "id": 34, "destination": {"commit": {"hash": "6689cfd44b98", "type": "commit", "links": {"self": {"href": "data/repositories/ignitionrobotics/ign-plugin/commit/6689cfd44b98.json"}, "html": {"href": "#!/ignitionrobotics/ign-plugin/commits/6689cfd44b98"}}}, "repository": {"links": {"self": {"href": "data/repositories/ignitionrobotics/ign-plugin.json"}, "html": {"href": "#!/ignitionrobotics/ign-plugin"}, "avatar": {"href": "data/bytebucket.org/ravatar/{f4e3de89-d527-44d3-b10f-fde17d644890}ts=c_plus_plus"}}, "type": "repository", "name": "ign-plugin", "full_name": "ignitionrobotics/ign-plugin", "uuid": "{f4e3de89-d527-44d3-b10f-fde17d644890}"}, "branch": {"name": "ign-plugin1"}}, "created_on": "2019-12-17T18:21:03.233094+00:00", "summary": {"raw": "While porting code from Gazebo-classic to Ignition, often some Gazebo 9 plugin sneakily hides inside an SDF / URDF file, happens to be on the path and we try to `dlopen` it. The problem is that this mixes 2 different versions of `ign-msgs`, which causes protobuf to throw an exception:\r\n\r\n~~~\r\n[libprotobuf ERROR google/protobuf/descriptor_database.cc:57] File already exists in database: ignition/msgs/time.proto                                                         \r\n[libprotobuf FATAL google/protobuf/descriptor.cc:1164] CHECK failed: generated_database_->Add(encoded_file_descriptor, size):\r\nterminate called after throwing an instance of 'google::protobuf::FatalException'   \r\n  what():  CHECK failed: generated_database_->Add(encoded_file_descriptor, size):  \r\n~~~\r\n\r\nThis causes the whole program to crash, and it's tough for the end user to realize what's going wrong. Ideally, we'd handle this more elegantly. Maybe something can be done on the `ign-msgs` side. But for now, I tried something here.\r\n\r\nThis try/catch block cleanly handles the situation for me, the following is printed, the library is ignored and simulation goes on:\r\n\r\n\r\n```\r\nException thrown while loading library [/home/chapulina/rmf/build/ros1/install/lib/libpayload_handler.so]\r\n[Err] [SystemLoader.cc:75] Failed to load system plugin [libpayload_handler.so] : couldn't load library on path [/home/chapulina/rmf/build/ros1/install/lib/libpayload_handler.s\r\no].\r\n```\r\n\r\nBut the catch (no pun intended) is that if I don't wrap the `dlopen` call with those sleeps, for some reason the program fails to catch protobuf's exception and crashes. I really don't understand how that would matter.\r\n\r\nReading answers like [this](https://stackoverflow.com/questions/413473/dlopen-on-library-with-static-member-that-throws-exception-in-constructor-resu) it sounds like we shouldn't be able to catch that exception in the first place, but somehow the sleeps make it work.", "markup": "markdown", "html": "<p>While porting code from Gazebo-classic to Ignition, often some Gazebo 9 plugin sneakily hides inside an SDF / URDF file, happens to be on the path and we try to <code>dlopen</code> it. The problem is that this mixes 2 different versions of <code>ign-msgs</code>, which causes protobuf to throw an exception:</p>\n<div class=\"codehilite\"><pre><span></span>[libprotobuf ERROR google/protobuf/descriptor_database.cc:57] File already exists in database: ignition/msgs/time.proto                                                         \n[libprotobuf FATAL google/protobuf/descriptor.cc:1164] CHECK failed: generated_database_-&gt;Add(encoded_file_descriptor, size):\nterminate called after throwing an instance of &#39;google::protobuf::FatalException&#39;   \n  what():  CHECK failed: generated_database_-&gt;Add(encoded_file_descriptor, size):  \n</pre></div>\n\n\n<p>This causes the whole program to crash, and it's tough for the end user to realize what's going wrong. Ideally, we'd handle this more elegantly. Maybe something can be done on the <code>ign-msgs</code> side. But for now, I tried something here.</p>\n<p>This try/catch block cleanly handles the situation for me, the following is printed, the library is ignored and simulation goes on:</p>\n<div class=\"codehilite\"><pre><span></span>Exception thrown while loading library [/home/chapulina/rmf/build/ros1/install/lib/libpayload_handler.so]\n[Err] [SystemLoader.cc:75] Failed to load system plugin [libpayload_handler.so] : couldn&#39;t load library on path [/home/chapulina/rmf/build/ros1/install/lib/libpayload_handler.s\no].\n</pre></div>\n\n\n<p>But the catch (no pun intended) is that if I don't wrap the <code>dlopen</code> call with those sleeps, for some reason the program fails to catch protobuf's exception and crashes. I really don't understand how that would matter.</p>\n<p>Reading answers like <a data-is-external-link=\"true\" href=\"https://stackoverflow.com/questions/413473/dlopen-on-library-with-static-member-that-throws-exception-in-constructor-resu\" rel=\"nofollow\">this</a> it sounds like we shouldn't be able to catch that exception in the first place, but somehow the sleeps make it work.</p>", "type": "rendered"}, "source": {"commit": {"hash": "ba4e61bb9898", "type": "commit", "links": {"self": {"href": "data/repositories/ignitionrobotics/ign-plugin/commit/ba4e61bb9898.json"}, "html": {"href": "#!/ignitionrobotics/ign-plugin/commits/ba4e61bb9898"}}}, "repository": {"links": {"self": {"href": "data/repositories/ignitionrobotics/ign-plugin.json"}, "html": {"href": "#!/ignitionrobotics/ign-plugin"}, "avatar": {"href": "data/bytebucket.org/ravatar/{f4e3de89-d527-44d3-b10f-fde17d644890}ts=c_plus_plus"}}, "type": "repository", "name": "ign-plugin", "full_name": "ignitionrobotics/ign-plugin", "uuid": "{f4e3de89-d527-44d3-b10f-fde17d644890}"}, "branch": {"name": "dlopen_exception"}}, "comment_count": 0, "state": "DECLINED", "task_count": 0, "participants": [], "reason": "We should look into a proper solution later", "updated_on": "2020-04-01T23:17:10.651552+00:00", "author": {"display_name": "Louise Poubel", "uuid": "{5cfa2075-477b-4ded-bdb9-8d2479544ec4}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D"}, "html": {"href": "https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:6ff86fcb-b7ab-44a5-b8a6-f6d9cae8b6e8/7d903d90-c5ea-4182-b7ef-0d467e9e1c74/128"}}, "nickname": "chapulina", "type": "user", "account_id": "557058:6ff86fcb-b7ab-44a5-b8a6-f6d9cae8b6e8"}, "merge_commit": null, "closed_by": {"display_name": "Louise Poubel", "uuid": "{5cfa2075-477b-4ded-bdb9-8d2479544ec4}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D"}, "html": {"href": "https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:6ff86fcb-b7ab-44a5-b8a6-f6d9cae8b6e8/7d903d90-c5ea-4182-b7ef-0d467e9e1c74/128"}}, "nickname": "chapulina", "type": "user", "account_id": "557058:6ff86fcb-b7ab-44a5-b8a6-f6d9cae8b6e8"}}